name: 🐞 Bug report
description: Report a bug to help us reproduce and fix it.
title: "[Bug] "
labels: ['Bug']

body:
- type: checkboxes
  attributes:
    label: Checklist
    options:
      - label: I searched related issues but found no solution.
      - label: The bug persists in the latest version.
      - label: Issues without environment info and a minimal reproducible demo are hard to resolve and may receive no feedback.
      - label: If this is not a bug report but a general question, please start a discussion in Issues. Otherwise, it will be closed.
      - label: Please use English. Otherwise, it will be closed.
- type: textarea
  attributes:
    label: Describe the bug
    description: A clear, concise description of the bug.
  validations:
    required: true
- type: textarea
  attributes:
    label: Reproduction
    description: Command/script run and configuration used.
    placeholder: Paste the command here.
  validations:
    required: true
- type: textarea
  attributes:
    label: Environment
    description: |
      Provide your environment info, including:
      - OS version
      - Python version
      - sglang-diffusion-routing version (`pip show sglang-diffusion-routing`)
      - Related dependency versions (fastapi, httpx, uvicorn)
    placeholder: Paste environment output here.
  validations:
    required: true
